version: "3.9"

services:
    frontend:
        build:
            context: ./front-end
            dockerfile: Dockerfile
        restart: always
        command : yarn start
        container_name: frontend
        ports:
            - "3000:3000"
    django:
        build:
            context: ./project
            dockerfile: Dockerfile
        command: python manage.py runserver
        container_name: back
        ports:
            - 8000:8000
        stdin_open: true
        depends_on:
            - frontend